### ISSUE TITLE
[BUG] Ensure integ tests run with security after plugin rename

### ISSUE THREAD

**Issue by cwperks** [opensearch-project/anomaly-detection#1025]
### Description

The security test workflow is currently skipping running tests with security quietly. See the example from the latest commit on main [here](https://github.com/opensearch-project/anomaly-detection/actions/runs/6103610427/job/16564313124) where `Run AD Test` is skipped. 

The expressions to set values in the github workflow are not getting executed as expected after the plugin was renamed to `time-series-analytics`

Specifically these lines:

```
plugin=`basename $(ls build/distributions/*.zip)`
version=`echo $plugin|awk -F- '{print $4}'| cut -d. -f 1-3`
plugin_version=`echo $plugin|awk -F- '{print $4}'| cut -d. -f 1-4`
qualifier=`echo $plugin|awk -F- '{print $5}'| cut -d. -f 1-1`
if $qualifier!=SNAPSHOT
then
  docker_version=$version-$qualifier
else
  docker_version=$version
fi
```

`echo $plugin|awk -F- '{print $4}'` is getting evaluated to `analytics` instead of `3.0.0.0` because of the extra hyphen in

```
opensearch-time-series-analytics-3.0.0.0-SNAPSHOT.zip
```

compared to

```
opensearch-anomaly-detection-3.0.0.0-SNAPSHOT.zip
```

**Comment by kaituo** [comment]
@cwperks Can we close the issue? It seems https://github.com/opensearch-project/anomaly-detection/pull/1023 have fixed it.

**Comment by cwperks** [comment]
Yes this can be closed. Closing now.
