### ISSUE TITLE
[BUG] MDS side navigation bar and breadcrumbs issue

### ISSUE THREAD

**Issue by jackiehanyang** [opensearch-project/anomaly-detection#1194]
**What is the bug?**
- When on list detector page, the first breadcrumbs `AnomalyDetection` is not jumping to the page with correct dataSourceId. Confirmed all other breadcrumbs work correctly, just this particular one on list page
- side navigation bar jumps correctly when a remote data source is selected. However, it's breaking when local cluster is chosen. It always jump to the page with default data source selected.

**Comment by minalsha** [comment]
Hi @jackiehanyang  does this issue still persist?
