### ISSUE TITLE
[FEATURE] Support date_nanos as a date field In Anomaly Detection. 

### ISSUE THREAD

**Issue by jehuty0shift** [opensearch-project/anomaly-detection#1226]
**Is your feature request related to a problem?**
Hi, Today, it is not supported to use a "date_nanos" field as a "time_field" for Anomaly Detection. Date nanos is a fully supported date type in OpenSearch and should be supported as such for AD. Creating a detector with such field will result in a Validation exception thrown by 
*validateTimeField* function here :   https://github.com/opensearch-project/anomaly-detection/blob/2.14/src/main/java/org/opensearch/ad/rest/handler/AbstractAnomalyDetectorActionHandler.java#L363

**What solution would you like?**
date_nanos should be validated as a date field.

**What alternatives have you considered?**
There is no alternatives beside having another time field which is of type "date"

**Do you have any additional context?**

I have created a custom plugin for validation for the index result name. In this plugin I could get around this limitation and validate the correct behavior of ad by reimplementing the Index and Validate Action and using customs **IndexAnomalyDetectorActionHandler** and   
**ValidateAnomalyDetectorActionHandler** which extend AbstractAnomalyDetectorActionHandler and override **validateTimeField** functions

I can work on a PR to update the validation process and write test to  but i don't really know which branch is the actual develop branch for 2.X (2.X and 2.14 look very different). I can spend some time on this since it will allow me to get rid of some code of my plugin and bring the functionality to all users. My plugin works and i can provide additional information. The full code however cannto be shared without approval of my organization (OVHcloud). 

Moreover i also know that OpenSearch Dashboards plugin has the same limitation in the dropdown list selection of time fields. The patch there is also quite starightforward. I did not yet open an issue on this project because I think it should be discussed here first.

**Comment by kaituo** [comment]
added support in both front and backend.
