### ISSUE TITLE
Don't replace detector's backend role when update

### ISSUE THREAD

**Issue by ylwu-amzn** [opensearch-project/anomaly-detection#124]
**Is your feature request related to a problem? Please describe.**
 
In current AD, when user create detector, we will set detector's backend role as user's backend role. When another user B update detector, will replace detector's backend role with this user B's backend role.

It is possible to deny a detector's creating user access through a series of detector update requests.  For example,
```
Users and Role Mappings: 
     CZ1 - czrole1
     CZ2 - czrole1, czrole2
     CZ3 - czrole2, czrole3
```
We can remove detector creator's access following these steps:
1. Create a detector with user CZ1. Then detector's backend role will be `czrole1`
2. Update detector description with user CZ2. Then detector backend role will change to  `czrole1, czrole2`
3. Update detector description with user CZ3. Then detector backend role will change to  `czrole2, czrole3`.
 
User CZ1 no longer has permission to access the detector they created. 

**Describe the solution you'd like**
One easy solution:
Don't replace detector's backend role when update detector. Detector's backend role will be fixed after created. 
User need to delete and recreate detector if needs to change detector's backend role.

**Describe alternatives you've considered**
User needs stricter permission control on monitor and detector, check https://github.com/opensearch-project/alerting/issues/82 and https://github.com/opensearch-project/anomaly-detection/issues/112

We can let user select backend role from his/her own backend role list when create detector. Admin should be able to update detector's backend role after creation.

**Comment by ylwu-amzn** [comment]
@skkosuri-amzn (alerting plugin) @eirsep (async search) @davidcui-amzn (reporting plugin) @bowenlan-amzn (ISM) @spbjss (ML), please keep an eye on this issue and let's follow the same design.

**Comment by davidcui-amzn** [comment]
@zhongnansu what's the Reporting back-end's current policy on this?

**Comment by ylwu-amzn** [comment]
Close this one as we have done code change in AD.
