### ISSUE TITLE
[FEATURE] Support missing value imputation

### ISSUE THREAD

**Issue by kaituo** [opensearch-project/anomaly-detection#1305]
**Is your feature request related to a problem?**
The Imputation option allows you to address missing data in your streams. You can choose from the following methods to handle gaps:

**What solution would you like?**
- **Ignore Missing Data (Default):** The system continues without factoring in missing data points, maintaining the existing data flow.
- **Fill with Custom Values:** Specify a custom value for each feature to replace missing data points, allowing for targeted imputation tailored to your data.
- **Fill with Zeros:** Replace missing values with zeros, ideal when the absence of data itself indicates a significant event, such as a drop to zero in event counts.
- **Use Previous Values:** Fill gaps with the last observed value, maintaining continuity in your time series data. This method treats missing data as non-anomalous, carrying forward the previous trend.

Using these options can improve recall in anomaly detection. For instance, if you're monitoring for drops in event counts, including both partial and complete drops, filling missing values with zeros helps detect significant data absences, improving detection recall.

**Comment by dblock** [comment]
[Catch All Triage - [1](https://github.com/dblock), [2](https://github.com/reta), [3](https://github.com/amistrn), [4](https://github.com/krisfreedain)]

**Comment by kaituo** [comment]
released in 2.17
