### ISSUE TITLE
Review Usages of actionGet API Call

### ISSUE THREAD

**Issue by aditjind** [opensearch-project/anomaly-detection#135]
Review Usages of actionGet API Call

**Describe the bug**
Review usages of actionGet API calls so that this API if being called in a single threaded pool should use timeouts or should be called asynchronously. 

PRs in alerting (https://github.com/opensearch-project/alerting/pull/130) and index management (https://github.com/opensearch-project/index-management/pull/100) where we have replaced the usages of the actionGet API calls which are blocking in nature and block the execution of the program with the callback listeners for the API call response. Using this API with time outs is okay but the execution should be made asynchronous. 

Sample Usage in Dashboards: 

https://github.com/opensearch-project/anomaly-detection/blob/cfebf07f637c05753e32a1648d05db98e1120e0f/src/main/java/org/opensearch/ad/util/ClientUtil.java#L184

We should review all such usages.

**Comment by ylwu-amzn** [comment]
No `actionGet` being used in AD code.
