### ISSUE TITLE
Release Beta 1

### ISSUE THREAD

**Issue by dblock** [opensearch-project/anomaly-detection#16]
- [x] CI passing
     - [x] Unit testing 
     - [x] Integration Tests #15 
- [ ] Manual testing
- [x] Release notes
- [x] Tag beta release
- [x] README
  - [x] badges
  - [x] links 
  - [ ] about section for the repo

**Comment by ylwu-amzn** [comment]
> Manual testing to match ODFE

Does this mean we will support migration from ODFE to OpenSearch?

**Comment by dblock** [comment]
> > Manual testing to match ODFE
> 
> Does this mean we will support migration from ODFE to OpenSearch?

I think I was trying to say that we should do as much testing as we did in ODFE. I removed the extra words.

**Comment by ylwu-amzn** [comment]
Beta1 released
