### ISSUE TITLE
[Meta] Support filtering in multi category high cardinality detector

### ISSUE THREAD

**Issue by sean-zheng-amazon** [opensearch-project/anomaly-detection#160]
**Is your feature request related to a problem? Please describe.**
The current baseline solution of multi category field HCAD doesn't provide filtering capability on individual fields. This has been asked by multiple users.

**Describe the solution you'd like**
To provide user interface to allow users filter the anomaly results based on individual fields.

**Comment by ohltyler** [comment]
Resolved in #261
