### ISSUE TITLE
Correct copyright notices to reflect Copyright OpenSearch Contributors

### ISSUE THREAD

**Issue by dblock** [opensearch-project/anomaly-detection#161]
Coming from https://github.com/opensearch-project/.github/issues/21.

The correct copyright for open-source projects in opensearch-project is "Copyright OpenSearch Contributors". Please correct any places that say otherwise, especially where it says copyright Amazon. Make sure NOTICE.txt and README match. See https://github.com/opensearch-project/.github/pull/24 for an example.

**Comment by ylwu-amzn** [comment]
We keep the old copyright for all class files created in ODFE, for example https://github.com/opensearch-project/anomaly-detection/blob/main/src/main/java/org/opensearch/ad/AnomalyDetectorPlugin.java#L13-L24

Should we remove this old copyright no matter if the file created in ODFE or not? 
If yes, should we remove this old copyright in branch 1.0?

**Comment by ylwu-amzn** [comment]
How about we change the label ? `bug` label seems misleading

**Comment by dblock** [comment]
You do not need to keep old Amazon copyright from ODFE in the code as we're rewriting it to be OpenSearch Contributors, we had consulted legal on this. 

You should make changes on main, do not backport to 1.0 (and probably no time to backport to 1.1 either).

**Comment by ylwu-amzn** [comment]
Got it. Sure, will remove the old Amazon copyright and merge to main branch.

**Comment by CEHENKLE** [comment]
@ylwu-amzn Hey, can this issue be closed?  Do you think you caught everything in #257 ?

Thanks!
/C

**Comment by ylwu-amzn** [comment]
Kept the issue as we haven't fixed frontend package. Now frontend copyright fixed https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/pull/118, will close this issue.

**Comment by AMoo-Miki** [comment]
The correct header for [this one](https://github.com/opensearch-project/anomaly-detection/blob/main/src/forbidden/ad-signatures.txt) is:

```
/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 */
```

**Comment by ylwu-amzn** [comment]
> The correct header for [this one](https://github.com/opensearch-project/anomaly-detection/blob/main/src/forbidden/ad-signatures.txt) is:
> 
> ```
> /*
>  * Copyright OpenSearch Contributors
>  * SPDX-License-Identifier: Apache-2.0
>  */
> ```

Thanks @AMoo-Miki , this file [`anomaly-detection/src/forbidden/ad-signatures.txt`](https://github.com/opensearch-project/anomaly-detection/blob/main/src/forbidden/ad-signatures.txt) is to define which copyright is wrong,
