### ISSUE TITLE
[BUG] The repo is undescribed

### ISSUE THREAD

**Issue by stockholmux** [opensearch-project/anomaly-detection#178]
**Describe the bug**
This repo lacks a description

**Other plugins installed**
N/a

**To Reproduce**
1. Go to https://github.com/opensearch-project/anomaly-detection/ in any browser
2. Look to the right, a little down from the top of the page
3. Instead of a user friendly description, you'll see something like this:

<img width="319" alt="Screen Shot 2021-08-16 at 3 35 40 PM" src="https://user-images.githubusercontent.com/1152927/129619850-c06d4003-68a5-4f04-848f-17c8aeb0b24c.png">

**Expected behavior**
To see a one-line description of what this repo does.

**Screenshots**
See above

**Comment by ylwu-amzn** [comment]
I see the description added 
```
Identify atypical data and receive automatic notifications
```
