### ISSUE TITLE
Add backwards compatibility tests for automation

### ISSUE THREAD

**Issue by VachaShah** [opensearch-project/anomaly-detection#188]
Add backwards compatibility tests for the plugin to automate end-to-end upgrade paths for faster releases. Developer documentation for implementing bwc tests and hooking them to CI: https://github.com/opensearch-project/opensearch-plugins/blob/main/TESTING.md#backwards-compatibility-testing

The tests have been added for the upgrade path of `1.13.0.0` to `1.1.0.0` plugin version with respective OpenSearch versions.
PRs:
1.  https://github.com/opensearch-project/anomaly-detection/pull/158
2. https://github.com/opensearch-project/anomaly-detection/pull/181
3. https://github.com/opensearch-project/anomaly-detection/pull/185

This issue is for adding tests for other upgrade paths for various versions and adding assertions for all the features.

**Comment by ylwu-amzn** [comment]
BWC added
