### ISSUE TITLE
Rename plugin

### ISSUE THREAD

**Issue by dblock** [opensearch-project/anomaly-detection#22]
**Is your feature request related to a problem? Please describe.**

Folder name (FolderID) is still using old naming (OpenDistro) .

Plugins should follow this naming convention:
Plugins ID / Folder Name after installation: opensearch-<pluginname> (All Lowercase)
Example ES: https://github.com/opensearch-project/index-management/blob/main/build.gradle#L104
Example Kibana: https://github.com/opensearch-project/index-management-dashboards-plugin/blob/main/package.json#L2
Plugin ZIP file Name: opensearch-<pluginname>-1.0.0.0-beta1.zip (All Lowercase)

**Comment by ylwu-amzn** [comment]
And we should rename `opendistro-job-scheduler` to `opensearch-job-scheduler` for all plugins depending on job scheduler like [AD](https://github.com/opensearch-project/anomaly-detection/blob/main/build.gradle#L97), [ISM](https://github.com/opensearch-project/index-management/blob/main/build.gradle#L107).
