### ISSUE TITLE
Use SNAPSHOT artifacts from maven for dependencies 

### ISSUE THREAD

**Issue by abbashus** [opensearch-project/anomaly-detection#242]
Coming from https://github.com/opensearch-project/opensearch-plugins/issues/45, use SNAPSHOT Maven dependencies from [aws.oss.sonatype.org](https://aws.oss.sonatype.org/content/repositories/snapshots). See https://github.com/opensearch-project/opensearch-plugins/blob/main/BUILDING.md#building-within-the-opensearch-build-system for details.

**Comment by sean-zheng-amazon** [comment]
this can be closed by https://github.com/opensearch-project/anomaly-detection/pull/286
