### ISSUE TITLE
[BUG] WARNING: Illegal reflective access by io.protostuff.runtime.PolymorphicThrowableSchema

### ISSUE THREAD

**Issue by jcgraybill** [opensearch-project/anomaly-detection#263]
**Describe the bug**
In OpenSearch 1.1, the following warning is emitted in the logfiles when the Anomaly Detection plugin is installed:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.protostuff.runtime.PolymorphicThrowableSchema (file:/home/ec2-user/opensearch-1.1.0/plugins/opensearch-anomaly-detection/protostuff-runtime-1.7.4.jar) to field java.lang.Throwable.cause
WARNING: Please consider reporting this to the maintainers of io.protostuff.runtime.PolymorphicThrowableSchema
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

Let's clean this up.

**Desktop (please complete the following information):**
 - OS: AL2 on EC2, x86_64
 - OpenSearch 1.1

**Comment by jcgraybill** [comment]
Let's fix one way or the other by 1.3.

**Comment by jcgraybill** [comment]
Hey, confirming, is this on track for 1.3?

**Comment by kaituo** [comment]
It is on track for 1.3 so far.

**Comment by ylwu-amzn** [comment]
Thanks @dblock to open issue to ask protostuff team to publish a new release https://github.com/protostuff/protostuff/issues/327
And the suggestion.
> Hand-building JARs is worse than this bug.
> The library hasn't been worked on for a year, so we either will need to find an alternative or start contributing/maintaining.

**Comment by dblock** [comment]
Closed via https://github.com/opensearch-project/anomaly-detection/pull/441, did not make it in 1.3, but will be in next.
