### ISSUE TITLE
Anomaly Detection: Add feature attribution and expected value to detector details page.

### ISSUE THREAD

**Issue by sean-zheng-amazon** [opensearch-project/anomaly-detection#299]
With OpenSearch 1.2, we will have feature attribution and expected value published in AD result index. But users have to use queries or build their own dashboard to see the values. We propose to expose these values in AD detail page for a better user experience. 

Current limitations - maximum 5 features supported at one time

![Screen Shot 2021-11-09 at 5 54 38 PM](https://user-images.githubusercontent.com/51798415/141035258-0133a150-3a36-4e70-8597-8ef8896a6ee2.png)

**Comment by alexahorgan** [comment]
Feature Review notes and feedback:
Anomaly Occurrences: Change the defaults for regular use cases and identify defaults for high cardinality use cases. 
Table Usability: Follow up during UX office hours to brainstorm on usability tables.

**Comment by Naarcha-AWS** [comment]
@sean-zheng-amazon and @alexahorgan: Do we have a development PR associated with feature attribution in AD? If so, can we link to this issue?

**Comment by ohltyler** [comment]
Resolved in #296

**Comment by sean-zheng-amazon** [comment]
We adjusted the interface a bit to accommodate the limitation from tooltip widget. Basically we separated the feature attribution/expected value in annotation instead of the flyout. See below for the new screen shots:

![feature-contribution-ad](https://user-images.githubusercontent.com/51798415/184191975-2606c949-093f-4354-b57f-5f442fac05fd.png)
![feature-output-ad](https://user-images.githubusercontent.com/51798415/184192001-c0928729-11ef-45b0-87a9-6892e2f1e060.png)
.
