### ISSUE TITLE
Default CI Java Version to Java 11, run tests on 8, 14 and 17

### ISSUE THREAD

**Issue by dblock** [opensearch-project/anomaly-detection#320]
Coming from https://github.com/opensearch-project/opensearch-plugins/issues/64, default CI Java version to 11 (LTS), and run tests on 8, 14 and 17.

- [ ] Change the default Java version for CI in GitHub actions from 14/15 to 11 (LTS).
- [ ] Add Java 8, 14 (used before), and 17 (next LTS) to the CI matrix.
- [ ] Document Java versions in DEVELOPER_GUIDE.md.

**Comment by dblock** [comment]
@ohltyler You still need to build on JDK 8

**Comment by ohltyler** [comment]
@dblock I thought 8 became optional. We had encountered some failures building with it:
```
11 = must, 8 = should, 14 and 17 = nice to have
```

**Comment by ohltyler** [comment]
What about JDK17? We also had problems with that one. Is that still optional? Is this issue out of date?

**Comment by ohltyler** [comment]
@dblock there's problems doing this with JDK8 - details in #409
