### ISSUE TITLE
Move to opensearch dashboard user agent

### ISSUE THREAD

**Issue by ylwu-amzn** [opensearch-project/anomaly-detection#34]
The [user agent](https://github.com/opensearch-project/anomaly-detection/blob/07a143be3b89fea6bf929bba8eeef9db9c4e9457/src/main/java/com/amazon/opendistroforelasticsearch/ad/util/RestHandlerUtils.java#L91) is still using "Kibana", we need to change to OpenSearch Dashboard like AD dashboard https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/blob/main/server/utils/constants.ts#L40

**Comment by spbjss** [comment]
PR: https://github.com/opensearch-project/anomaly-detection/pull/56
