### ISSUE TITLE
Incremented version to 1.2.5

### ISSUE THREAD

**Issue by abhinavGupta16** [opensearch-project/anomaly-detection#379]
Incremented version to 1.2.5 following from https://github.com/opensearch-project/opensearch-build/issues/1600 to prepare for the next possible release

**Comment by ohltyler** [comment]
@abhinavGupta16 not sure what this is, can it be closed?

**Comment by abhinavGupta16** [comment]
This is adding 1.2.5 increments to the 1.2 branch and backport to ensure a swift release if and when required.

**Comment by ohltyler** [comment]
Is there an ongoing release plan for a version 1.2.5? We've never bumped versions before unless there was a set plan to release it

**Comment by amitgalitz** [comment]
@abhinavGupta16 closing this since we are about to release 1.3, re-open if there is a case for this issue to remain open.
