### ISSUE TITLE
Refactor validateAnomalyDetectorFeatures method so that it can be re-used for more use cases

### ISSUE THREAD

**Issue by yizheliu-amazon** [opensearch-project/anomaly-detection#39]
**Is your feature request related to a problem? Please describe.**
Refactor `validateAnomalyDetectorFeatures` method so that it can be re-used for more use cases. More context: https://github.com/opensearch-project/anomaly-detection/pull/20#discussion_r625450977

**Describe the solution you'd like**
Same as above 

**Describe alternatives you've considered**
N/A

**Additional context**
https://github.com/opensearch-project/anomaly-detection/pull/20#discussion_r625450977

**Comment by ylwu-amzn** [comment]
This change done in this PR https://github.com/opensearch-project/anomaly-detection/pull/231
