### ISSUE TITLE
Remove mapping types

### ISSUE THREAD

**Issue by dreamer-89** [opensearch-project/anomaly-detection#394]
As part of v2.0 release, `mapping types` are getting removed from OpenSearch engine. Below are the changes in the opensearch-engine.
- Removal of type from rest end-points
- Removal of include_type_name parameter from API requests.

As part of this issue, please verify if type removal change on OpenSearch engine impacts this repository. If yes, then please remove the type references/usage from this plugin. 

Top level changes are captured in gist below: 
https://gist.github.com/dreamer-89/d76eaf639171e8ab32fa7f8b9d6c93d3

For more detailed changes, please check meta issue below:
Related: [OpenSearch-engine meta issue](https://github.com/opensearch-project/opensearch/issues/1940)

**Comment by ohltyler** [comment]
After a quick search in the plugin, I see mapping types are used in a few places to init system indices, using `mapping()` method ([example](https://github.com/opensearch-project/anomaly-detection/blob/main/src/main/java/org/opensearch/ad/indices/AnomalyDetectionIndices.java#L600)). Note this method is now `@deprecated` in `main` branch of OpenSearch, which is tracking 2.0.0 ([ref](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/action/admin/indices/create/CreateIndexRequest.java#L233))

**Comment by dreamer-89** [comment]
@ohltyler: Thank you for the update here. 
Is there a way we can find out all places which are impacted ? Will running integration tests (against OpenSearch main) help in identifying all breaking changes ?

**Comment by ohltyler** [comment]
As discussed separately offline, the campaign for removing mapping types at the API-level in core OpenSearch is done, which I believe is the only way this is used in this plugin. I will use a forked version, bump to 2.0, and run the integ tests using OpenSearch core 2.0.0 to highlight any initial problems.

**Comment by amitgalitz** [comment]
In addition it seems like we return "type:_doc" on responses to delete API, search detector and search detector tasks or results on Opensearch 2.0.0
