### ISSUE TITLE
Deprecate the "Master" nomenclature

### ISSUE THREAD

**Issue by tlfeng** [opensearch-project/anomaly-detection#397]
**Is your feature request related to a problem? Please describe.**
[OpenSearch](https://github.com/opensearch-project/OpenSearch) repository is going to replace the terminology "master"with "cluster manager".
issue: https://github.com/opensearch-project/OpenSearch/issues/472#issuecomment-960298995, with the plan for its terminology replacement.

Although the existing usages with "master" will be supported in OpenSearch version 2.x to keep the backwards compatibility, please prepare for the nomenclature change in advance, and replace all the usages with "master" terminology in the code base.
All the OpenSearch REST APIs and settings that contain "master" terminology will be deprecated in 2.0, and alternative usages will be added.

**Describe the solution you'd like**
Replace the terminology "master" with "cluster manager".

When being compatible with OpenSearch 2.0:
- Replace "master" in code comment and internal variable / class name.
Specifically, internal class name https://github.com/opensearch-project/anomaly-detection/blob/1.3.1.0/src/main/java/org/opensearch/ad/cluster/MasterEventListener.java

When being compatible with OpenSearch 3.0:
- Replace "master" in the reference to OpenSearch Java API 
(most of the new APIs are available in version 2.2, except `AcknowledgedResponse`)
  - [x] import org.opensearch.cluster.LocalNodeMasterListener -> LocalNodeClusterManagerListener
  - [x] clusterManagerService.onMaster() / offMaster() -> onclusterManager() / offClusterManager()
  - [x] DiscoveryNodes.Builder().masterNodeId() -> clusterManagerNodeId()
  - [ ] import org.opensearch.action.support.master.AcknowledgedResponse -> import org.opensearch.action.support.clustermanager.AcknowledgedResponse (will be available in version 3.0)

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by amitgalitz** [comment]
I began this process by replacing any variable, logs or comments with the use of "master" to "clusterManager" (https://github.com/opensearch-project/anomaly-detection/pull/504). This process will continue when Opensearch Core makes further changes to classes and methods that AD is using with this terminology.

**Comment by dblock** [comment]
For 2.0, at a minimum please ensure that the plugin is not calling any deprecated APIs in core or another plugin, and confirm below, then remove the 2.0.0 label. If you have time, do the complete deprecation as described in this issue.

**Comment by amitgalitz** [comment]
@dblock Any leftover uses of "master" are from classes in Opensearch that haven't been changed yet. To my understanding this isn't something that will be done until 3.0. Anything that could have been removed for 2.0 has already been removed with the mentioned PR above. For example (https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/cluster/LocalNodeMasterListener.java) and other classes, folder and etc. Any comments or logs have been changed in AD.

**Comment by dblock** [comment]
I think any leftovers will be done in 2.x, so I labeled this for v2.1.0.

**Comment by tlfeng** [comment]
Hi @dblock, I confirmed that @amitgalitz is correct that usages of "master" in OpenSearch Java APIs (public field, method, class, and package names) will be replaced in OpenSearch version 3.0, which is tracked in issue https://github.com/opensearch-project/OpenSearch/issues/1684, and I haven't started yet. The plugins can only replace these usages when the public Java APIs are renamed in OpenSearch repository, and I will keep update on this progress.

**Comment by ohltyler** [comment]
@amitgalitz is there any changes left on the AD side?

**Comment by anasalkouz** [comment]
Java APIs completed and released on 2.2 except for AcknowledgedResponse.
@amitgalitz Could you please complete the remaining part from your end? let's target 2.3 for all usages except for AcknowledgedResponse (there will be separate issue to track it).

**Comment by ohltyler** [comment]
All are resolved in #644 besides the `AcknowledgedResponse` change which won't be available until 3.0.

@anasalkouz if there will be a separate issue for that, should we close this issue now?

**Comment by ohltyler** [comment]
Please reopen if necessary.
