### ISSUE TITLE
[BUG] Detector stuck in Initializing state

### ISSUE THREAD

**Issue by danotorrey** [opensearch-project/anomaly-detection#400]
**Describe the bug**
When I create a detector, it initializes successfully the first time it is started. Then, when stopping and starting it again, it stays stuck at "Initializing" for multiple days and never seems to come out of the Initializing state. If I restart the OpenSearch node, the detector successfully reaches the "Running" state within an hour. If I stop/start the detector, the same problem happens again.  

**Other plugins installed**
Running these two images in separate docker containers: 
- opensearchproject/opensearch:1.1.0
- opensearchproject/opensearch-dashboards:1.1.0

**To Reproduce**
The issue seems to be reproducible by:
1. Create a new detector. Let is start and initialize to the running state successfully (while feeling in sample data).
2. Stop the detector, start it.
3. The detector seems to stay stuck in the initializing state for more than 24 hours. Restarting OpenSearch seems to be the only way to get it running again. After a restart, it seems to initialize quickly.

**Expected behavior**
The detector to restart successfully once started again.

**Screenshots**
![image](https://user-images.githubusercontent.com/3423655/157883929-24f3c783-06a4-4c65-b575-6fbc54b704e5.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 1.1 and 1.2

**Additional context**

**Comment by danotorrey** [comment]
I have updated the description with additional details and steps to reproduce the issue.

**Comment by sean-zheng-amazon** [comment]
@danotorrey thanks for detecting and reporting the issue! we'd need to know a bit more about your data set in order to reproduce this, are you using one of the sample data set from opensearch dashboard?

**Comment by kaituo** [comment]
I can reproduce the bug locally.  Will send a PR to fix it soon.

**Comment by danotorrey** [comment]
Thanks a lot for the fix @kaituo!
