### ISSUE TITLE
[BUG] Remove hand-built protostuff

### ISSUE THREAD

**Issue by dblock** [opensearch-project/anomaly-detection#416]
**Describe the bug**

In https://github.com/opensearch-project/anomaly-detection/pull/374 we have built protostuff on a developer machine to fix https://github.com/opensearch-project/anomaly-detection/issues/263, and checked it in to unblock the build. 

**Expected behavior**
Do not commit hand-built JARs and build from source/pull from maven.

**Comment by sean-zheng-amazon** [comment]
Given the fix depends on the availability of new protostuff release from maven, we decided to remove this from 1.3, will leave it open till protostuff version available.
