### ISSUE TITLE
[BUG] ParseUtils.java:149: warning - Tag @link: reference not fou nd: AggregatorFactories.Builder

### ISSUE THREAD

**Issue by dblock** [opensearch-project/anomaly-detection#423]
**Describe the bug**
The following warning appears a lot in the build.

```
ParseUtils.java:149: warning - Tag @link: reference not found: AggregatorFactories.Builder
```

**Comment by amitgalitz** [comment]
Have you seen this show up on a particular AD Action run or just building locally? I don't see this warning when running `./gradlew :build`

**Comment by amitgalitz** [comment]
I don't see this line at all in AD build. Reopen if you have a link to a github action that leads to this or steps to reproduce including JDK runtime and other environment details.
