### ISSUE TITLE
Add support for build version qualifiers.

### ISSUE THREAD

**Issue by dblock** [opensearch-project/anomaly-detection#432]
Coming from https://github.com/opensearch-project/opensearch-build/issues/1632, add support for `-Dbuild.version_qualifier=`. 

The distribution build process now supports passing additional optional qualifiers other than the 3 digit versions, e.g. `2.0.0-alpha1`. Add the ability to pass additional qualifier to build scripts, and generate artifacts with a version that includes the qualifier.

**Comment by amitgalitz** [comment]
Understand how this works for Opensearch core or plugins like common-utils that get picked up for maven build. For something like AD what are the ways this will be used for an AD build. Will the qualifier potentially get added to the manifest for each plugin?

**Comment by peterzhuamazon** [comment]
https://github.com/opensearch-project/anomaly-detection/pull/468
https://github.com/opensearch-project/anomaly-detection/pull/472
https://github.com/opensearch-project/opensearch-build/pull/1838
