### ISSUE TITLE
[BUG] Plugin contains checked in JARs with unclear provenance

### ISSUE THREAD

**Issue by dblock** [opensearch-project/anomaly-detection#433]
**Describe the bug**

The lib/randomcutforest-parkservices-2.0.1.jar and randomcutforest-core-2.0.1.jar JARs have unclear provenance. These need to be external dependencies. Code comes from https://github.com/aws/random-cut-forest-by-aws

**Comment by cliu123** [comment]
@dblock @amitgalitz There're zip files remaining in the AD plugin repo, for example: https://github.com/opensearch-project/anomaly-detection/tree/main/src/test/resources/org/opensearch/ad/bwc/anomaly-detection/1.1.0.0-SNAPSHOT

**Comment by amitgalitz** [comment]
Yes I am aware of this, will send a PR in the next 30 minutes to remove those.

**Comment by amitgalitz** [comment]
@dblock re-opened https://github.com/opensearch-project/anomaly-detection/issues/17 regarding this. This issue is related to JAR files we used to have manually added to our repo
