### ISSUE TITLE
Rename dependency namespaces

### ISSUE THREAD

**Issue by ohltyler** [opensearch-project/anomaly-detection#45]
Once the `common-utils` and `job-scheduler` plugins have renamed their namespaces to `org.opensearch.*`, rename the remaining imports that are still using the old namespace.

See [here](https://github.com/opensearch-project/anomaly-detection/pull/43#discussion_r632633694) for more details.

**Comment by tlfeng** [comment]
The namespaces for Job Scheduler plugin has been moved from `com.amazon.opendistroforelasticsearch` to `org.opensearch` in `main` branch.

**Comment by ylwu-amzn** [comment]
Fixed in https://github.com/opensearch-project/anomaly-detection/pull/47
