### ISSUE TITLE
Update job scheduler extension meta file

### ISSUE THREAD

**Issue by ylwu-amzn** [opensearch-project/anomaly-detection#46]
AD extends job scheduler to implement its own job. We need to update [the extension file](https://github.com/opendistro-for-elasticsearch/anomaly-detection/blob/main/src/main/resources/META-INF/services/com.amazon.opendistroforelasticsearch.jobscheduler.spi.JobSchedulerExtension) name and AD plugin class path.

**Comment by tlfeng** [comment]
The package of `JobSchedulerExtension` interface has been moved from`com.amazon.opendistroforelasticsearch.jobscheduler.spi` to `org.opensearch.jobscheduler.spi`.
Please refer to [this sample file](https://github.com/opensearch-project/job-scheduler/blob/45c12adfa4f9ca69734d34a7e43d9fa8b11334d5/sample-extension-plugin/src/main/resources/META-INF/services/org.opensearch.jobscheduler.spi.JobSchedulerExtension) for the usage. 😁

**Comment by ylwu-amzn** [comment]
This is already done.
