### ISSUE TITLE
Re-enable Docker Image run and AD tests in CI workfow

### ISSUE THREAD

**Issue by aksingh-es** [opensearch-project/anomaly-detection#491]
Currently OS 2.0  docker image is unavailable.So for the CI to succeed,CI.yml  AD tests run dependent on the docker image has been commented out.
Ref: https://github.com/opensearch-project/anomaly-detection/pull/464

Opening this issue as placeholder to follow up and uncomment the tests once docker is available .

**Comment by dblock** [comment]
Do we still want this for 2.0?

**Comment by aksingh-es** [comment]
yes..this is a necessary infra issue and 2.0 specific..so we can remove the label but will keep the issue open as placesholder
