### ISSUE TITLE
Refactor AD code to improve testability

### ISSUE THREAD

**Issue by Zhangxunmt** [opensearch-project/anomaly-detection#518]
This is related to the test issues discussed in #424 and  #493 . AD still has a long list of classes that could not meet the test coverage bar. 

One dominate reason for lacking tests coverage is that some classes in AD have super long and complicated functions which are difficult to be tested. To resolve this problem, we need to refactor those untested classes and decouple the complexities into smaller sub-functions.  

After the first scan of the Jacoco test exclusive list, the following classes needs refactor before adding more unit tests. 

[DeleteAnomalyDetectorTransportAction](https://github.com/opensearch-project/anomaly-detection/blob/main/src/main/java/org/opensearch/ad/transport/DeleteAnomalyDetectorTransportAction.java)
[SearchAnomalyResultTransportAction](https://github.com/opensearch-project/anomaly-detection/blob/main/src/main/java/org/opensearch/ad/transport/SearchAnomalyResultTransportAction.java)
[AnomalyResultBulkIndexHandler](https://github.com/opensearch-project/anomaly-detection/blob/main/src/main/java/org/opensearch/ad/transport/handler/AnomalyResultBulkIndexHandler.java)
[ADTaskManager](https://github.com/opensearch-project/anomaly-detection/blob/main/src/main/java/org/opensearch/ad/task/ADTaskManager.java)
[ADBatchTaskRunner](https://github.com/opensearch-project/anomaly-detection/blob/main/src/main/java/org/opensearch/ad/task/ADBatchTaskRunner.java)
[AnomalyDetectorRunner](https://github.com/opensearch-project/anomaly-detection/blob/main/src/main/java/org/opensearch/ad/AnomalyDetectorRunner.java)
[AnomalyDetectorJobRunner](https://github.com/opensearch-project/anomaly-detection/blob/main/src/main/java/org/opensearch/ad/AnomalyDetectorJobRunner.java)
[ModelValidationActionHandler](https://github.com/opensearch-project/anomaly-detection/blob/main/src/main/java/org/opensearch/ad/rest/handler/ModelValidationActionHandler.java)
[ModelValidationActionHandler](https://github.com/opensearch-project/anomaly-detection/blob/main/src/main/java/org/opensearch/ad/rest/handler/ModelValidationActionHandler.java)
[RestStatsAnomalyDetectorAction](https://github.com/opensearch-project/anomaly-detection/blob/main/src/main/java/org/opensearch/ad/rest/RestStatsAnomalyDetectorAction.java)
[RestValidateAnomalyDetectorAction](https://github.com/opensearch-project/anomaly-detection/blob/main/src/main/java/org/opensearch/ad/rest/RestValidateAnomalyDetectorAction.java)
[RestIndexAnomalyDetectorAction](https://github.com/opensearch-project/anomaly-detection/blob/main/src/main/java/org/opensearch/ad/rest/RestIndexAnomalyDetectorAction.java)

**Comment by Zhangxunmt** [comment]
One example for refactoring https://github.com/opensearch-project/anomaly-detection/pull/517

**Comment by ohltyler** [comment]
@Zhangxunmt would you consider this resolved or is there more files needed to refactor?

**Comment by Zhangxunmt** [comment]
It's partially done. Only a few are removed from the jacoco exclusion list. We can close this issue and track the same in this one https://github.com/opensearch-project/anomaly-detection/issues/424.
