### ISSUE TITLE
Publish plugin zips to maven repo

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/anomaly-detection#525]
### Description

With existing setup the plugin jars are only published to maven repo, but not the generated plugin zips.

### Related META issue

https://github.com/opensearch-project/opensearch-build/issues/1916

### Current Behavior

Existing all maven publications target the jar files to publish to maven, but not the generated distribution zips.

### Expected Behavior

Along with plugin jars, plugin zips should also be published to maven repo with right maven coordinates, so user can download these plugins using dependancy model.

### Steps To Reproduce

1. Run the gradle assemble task that outputs jar and zips.
2. Using build setup the jars are published to local staging maven repo.
3. Zip's are just added to distribution's folder during build runtime.
4. Finally once build is done, just the jar files are added to local maven repo and updates to the manifest file, but not the zips.

### Proposed solution
A custom gradle plugin solution that can create the publication task for the zips to get published to local staging maven repo with right maven coordinates.
Add/Configure the custom gradle plugin openseearch.pluginzip to the gradle project and test the generated plugin zip's to upload to local maven repo.
More details on how to use the Plugin:
https://github.com/opensearch-project/opensearch-plugins/blob/main/BUILDING.md#opensearchpluginzip

**Comment by prudhvigodithi** [comment]
Hey @amitgalitz you can check example of [job-scheduler](https://github.com/opensearch-project/job-scheduler/pull/182) PR, also there is a proposal to add a setting in default [build.sh](https://github.com/opensearch-project/opensearch-build/pull/1999/files) for the plugins that does not manage the build scripts, But I would suggest you to go ahead and create a build.sh from the AD plugin.
@dblock @bbarani @peterzhuamazon

**Comment by prudhvigodithi** [comment]
Hey @sean-zheng-amazon @amitgalitz @ylwu-amzn, just following up to see if `opensearch.pluginzip` is integrated, if not please make the necessary changes to add `opensearch.pluginzip` to support publishing your zips to Maven.

**Comment by bbarani** [comment]
@amitgalitz @sean-zheng-amazon Can you please update the status on changes to your build script to publish plugin zip to maven?

**Comment by amitgalitz** [comment]
@bbarani I'll have a PR out for this today
