### ISSUE TITLE
[BUG] CI link to download the job-scheduler artifacts needs to be updated

### ISSUE THREAD

**Issue by zelinh** [opensearch-project/anomaly-detection#527]
**What is the bug?**
AD changed to get job-scheduler artifacts from CI link to run integCluster (https://github.com/opensearch-project/anomaly-detection/pull/487) and now it gets the artifacts from this link like this: `https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.3.2/latest/linux/x64/builds/opensearch/plugins/opensearch-job-scheduler-1.3.2.0.zip`
However from the PR here, https://github.com/opensearch-project/opensearch-build/pull/1807, we added an additional folder `tar` in the path to support both tarball and rpm distribution. This will need to be updated with the new CI link to get the latest job-scheduler artifacts.

**How can one reproduce the bug?**

**What is the expected behavior?**

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by amitgalitz** [comment]
Okay to close this as we are making this change in the several 1.3.2 version bumps PR we have out 😮  ?

**Comment by amitgalitz** [comment]
This has been fixed with 1.3.2 version bump PR. https://github.com/opensearch-project/anomaly-detection/pull/485
