### ISSUE TITLE
[BUG] ODFE References and out-of-date links

### ISSUE THREAD

**Issue by ahopp** [opensearch-project/anomaly-detection#55]
**Describe the bug**
There are still a couple of references to OpenDistro across the experience. 

1. "Read about Get started with Anomaly detection" links to https://opendistro.github.io/for-elasticsearch-docs/docs/ad/ rather than https://docs-beta.opensearch.org/docs/ad/.
2. Sample detector "Monitor HTTP responses" includes ODFE language (ex. **opendistro**-sample-http-responses-detector & **opendistro**-sample-http-responses).
3. Sample detector "Monitor eCommerce orders" includes ODFE language (ex. **opendistro**-sample-ecommerce-detector & **opendistro**-sample-ecommerce).
4. Sample detector "Monitor host health" includes ODFE language (ex. **opendistro**-sample-host-health-detector & **opendistro**-sample-host-health).
5. "Looking to get more familiar with anomaly detection? Read the documentation or create a sample detector to get started." points to https://opendistro.github.io/for-elasticsearch-docs/docs/ad/ rather than https://docs-beta.opensearch.org/docs/ad/.

**Other plugins installed**
N/A

**To Reproduce**
1. Go to 'Anomaly detection'
2. Click on 'Sample detectors' or 'Create detector'
3. See error

**Expected behavior**
Links to correct documentation and no references to ODFE. 

**Screenshots**

![image](https://user-images.githubusercontent.com/9532728/119094452-e5cc4f00-b9c5-11eb-8195-c45fa3621507.png)
![image](https://user-images.githubusercontent.com/9532728/119094486-f41a6b00-b9c5-11eb-8172-4c345c88b8a0.png)

**Comment by ohltyler** [comment]
Fixed in https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/pull/24
