### ISSUE TITLE
[FEATURE] Anomaly detection alert - access to different event fields

### ISSUE THREAD

**Issue by eslam-gomaa** [opensearch-project/anomaly-detection#604]
Hi
we're using Anomaly detection, and when creating alerts I see that `ctx.results` variables contains **ONLY** the field used to categorize the anomalies (in our case we need to have access to the different event fields in order to produce a usable and clear alert message)

Is there a way to access different event fields while creating an alert  ? 

![image](https://user-images.githubusercontent.com/33789516/176997799-ce8fdf8e-9749-4cc3-aece-31ec8d65cbf6.png)

### Here is a sample result of `ctx.results` variable
> **NOTE** I tired to create a field contains multiple fields (as an array) but `ctx.results` returns only the 0 index 

![image](https://user-images.githubusercontent.com/33789516/176997977-9e81aaec-379c-473c-aaa0-4cf989e03f29.png)

**Host/Environment (please complete the following information):**

 AWS Opensearch service with Elasticsearch 7.10.2

**Comment by kaituo** [comment]
Does https://forum.opensearch.org/t/find-result-of-anomaly-detection-through-ctx-results-0-for-monitor/7461/2 answer your question?

**Comment by eslam-gomaa** [comment]
Hi @kaituo 
Actually all what I want is to know how to get more fields into the `entity` section (like [Here](https://forum.opensearch.org/t/find-result-of-anomaly-detection-through-ctx-results-0-for-monitor/7461))

![image](https://user-images.githubusercontent.com/33789516/177874256-102ea27d-487c-4022-aaa6-d9dda8f6b675.png)

---

**To be more specific about my case:** what I specify in the `category_field` is what inserted into the `entity section`

And **I can only specify only 1 `category field`** through Kibana or APIs

![image](https://user-images.githubusercontent.com/33789516/177873245-f7b83437-21e0-404f-840c-03bd725665f0.png)

![image](https://user-images.githubusercontent.com/33789516/177873393-d2e24b51-3cea-4622-a994-5f9f3a77f38a.png)

**Comment by kaituo** [comment]
Which versions of OpenSearch do you use? We start supporting multiple category field since 1.1.
