### ISSUE TITLE
[Feature] Support remote cluster index on FGAC domains

### ISSUE THREAD

**Issue by ylwu-amzn** [opensearch-project/anomaly-detection#609]
**What is the bug?**
We can't create detector on remote cluster indices from ES7.9 as we add FGAC for AD plugin from ES7.9

**How can one reproduce the bug?**
1. Set up two security-enabled clusters on AWS OpenSearch Service
2. Configure remote cluster
3. Create detector on remote cluster index
4. It will fail, sample response 
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "security_exception",
        "reason" : "No user found for indices:data/read/search"
      }
    ],
    "type" : "security_exception",
    "reason" : "No user found for indices:data/read/search"
  },
  "status" : 500
}

```

**What is the expected behavior?**
Should be able to create anomaly detector on remote cluster index and can run it correctly.

**What is your host/environment?**
 - Version: ES7.9 + 
 - Plugins: anomaly-detection

**Do you have any screenshots?**
No

**Do you have any additional context?**
No

**Comment by kaituo** [comment]
We have some basic support (by asking cx to put fields manually) in UX: https://github.com/opendistro-for-elasticsearch/anomaly-detection-kibana-plugin/pull/244

For FGAC domains, AD won't work even if cross cluster search works.

A few customers have asked about it.

**Comment by amitgalitz** [comment]
remote index is now fully supported on FGAC and non FGAC domains from OS 2.17 and on. https://github.com/opensearch-project/anomaly-detection/pull/1290
