### ISSUE TITLE
Implement OpenSearch core branching strategy

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/anomaly-detection#614]
### Description

Ensure `MAJOR_VERSION.x` branch exists, the `main` branch acts as source of truth effectively working on 2 versions at the same time.

### Related META issue

https://github.com/opensearch-project/opensearch-plugins/issues/142

### Current Behavior

Currently plugins follow a branching strategy where they work on `main` for the next development iteration, effectively working on 2 versions at the same time. This is not always true for all plugins, the release branch or branch pattern is not consistent, the lack of this standardization would limit multiple automation workflows and alignment with core repo. More details on [META ISSUE](https://github.com/opensearch-project/opensearch-plugins/issues/142)

### Proposed solution

Follow OpenSearch [core branching](https://github.com/opensearch-project/.github/blob/main/RELEASING.md#opensearch-branching). Create `1.x` and `2.x` branches, do not create `2.0` as a branch of main, instead create `main -> 2.x -> 2.0`. Maintain working CI for 3 releases at any given time.

**Comment by amitgalitz** [comment]
@prudhvigodithi we already have a maintained 2.x branch in AD, is the only thing left to move main to 3.0.0-SNAPSHOT? In order to do that, do I have the go ahead to send out PRs to increment job-scheduler and common utils main to 3.0.0? Additionally any other insight on questions I had on the main meta issue?

**Comment by prudhvigodithi** [comment]
Hey @amitgalitz I have added a reply please check 
https://github.com/opensearch-project/opensearch-plugins/issues/142#issuecomment-1185858208
So you just have to branch to make sure you support 3 releases at any given time `main` should be nexts major version, 2.x for next minor version, 2.2 for upcoming v2.2.0 release.

So this case since anomaly-detection depends on job-scheduler and common utils, we have to make sure job-scheduler and common utils also follows the above branching so that AD 2.x can use job-scheduler and common utils 2,x and 2.2 of AD can look for job-scheduler and common utils 2.2.
Please let me know if I did answer your question.

**Comment by prudhvigodithi** [comment]
Hey @amitgalitz @sean-zheng-amazon can you please post an update on this branching strategy?
@CEHENKLE

**Comment by amitgalitz** [comment]
> Hey @amitgalitz @sean-zheng-amazon can you please post an update on this branching strategy? @CEHENKLE

Hi @prudhvigodithi we are planning on updating AD main branch to 3.0.0-SNAPSHOT however this is blocked due to us depending on Job-scheduler to bump to 3.0.0-SNAPSHOT first. Because of this I opened a PR https://github.com/opensearch-project/job-scheduler/pull/206 on JS to bump main a week ago but have had BWC test failures. Might need some suggestion on fixing that PR to help move it forward.

**Comment by ohltyler** [comment]
I've left a comment on https://github.com/opensearch-project/job-scheduler/pull/206. Re-labeling as 2.3 since this is a blocker for us to move `main` to `3.0` just yet.

**Comment by ohltyler** [comment]
We are still blocked on this due to https://github.com/opensearch-project/job-scheduler/pull/229

**Comment by dblock** [comment]
There should be nothing blocking this rn. To close this issue:

- [ ] main is building 3.0
- [ ] 2.x is building next 2.x, which is currently 2.4.0
- [ ] 2.3 is building next 2.3, which is 2.3.1
- [ ] manifests in https://github.com/opensearch-project/opensearch-build/tree/main/manifests include all 3
