### ISSUE TITLE
Bump jackson and snakeyaml dependencies

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/anomaly-detection#676]
**Is your feature request related to a problem?**
Core has bumped jackson and snakeyaml dependencies [here](https://github.com/opensearch-project/OpenSearch/pull/4556) to 2.13.4 and 1.32 respectively for versions 2.x, 2.3 , 2.2 , 2.1 , 2.0, 1.3 and 1.x. Plugin and client teams should do the same to align with core.

**What solution would you like?**

**What alternatives have you considered?**

**Do you have any additional context?**

**Comment by amitgalitz** [comment]
Is this not required for 2.3.1?

**Comment by owaiskazi19** [comment]
> Is this not required for 2.3.1? @minalsha

@amitgalitz core has updated the dependencies for the above versions mentioned (2.x, 2.3 , 2.2 , 2.1 , 2.0, 1.3 and 1.x). So it's better to keep the plugins on the same version to avoid the conflict.

**Comment by bbarani** [comment]
@amitgalitz We are currently not looking to do 2.3.1 release but it might change if we end up fixing any critical patches in 2.3.0 release. Can you please let us know the plan for 2.4.0?

**Comment by amitgalitz** [comment]
This fix has been backported too 2.x so will be a part of the 2.4.0 release.

**Comment by amitgalitz** [comment]
Closing this issue as we backported the change to future potential 2.3.1, 2.4.0, 1.3.6 releases
