### ISSUE TITLE
[BUG] AD doesn't compile: BaseNodeRequest class has been removed

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/anomaly-detection#687]
**What is the bug?**

Classes extending `BaseNodeRequest` now produce compile errors.

**How can one reproduce the bug?**

Compile against OpenSearch main branch (3.0.0 snapshot dependency)

**What is the expected behavior?**
Code compiles

**What is your host/environment?**
Jenkins CI on this project

**Do you have any screenshots?**
https://github.com/opensearch-project/anomaly-detection/actions/runs/3223621043/jobs/5273892781

**Do you have any additional context?**
[#4702](https://github.com/opensearch-project/OpenSearch/pull/4702) removed the (deprecated) `BaseNodeRequest` class.
Relevant comments:

> ```
> * @deprecated this class is deprecated and classes will extend TransportRequest directly
>  */
> // TODO: this class can be removed in main once 7.x is bumped to 7.4.0
> ```

I attempted to fix in #688 with a cherry-pick of this commit:  https://github.com/opensearch-project/anomaly-detection/pull/686/commits/b97935983f63ffa7989c7c0355bf03e45ee1e96a

But it seems the new `TransportNodesAction` class signature (also updated in that PR) isn't getting pulled into the dependency and is still using an old copy of the class.

**Comment by dbwiddis** [comment]
OK, I'm confused.  I think you're pulling from an older external dependency here, while on `feature/extensions` we're pulling from main.    So this is not a bug _yet_ but it will become one when you update to the next version of OpenSearch...

**Comment by amitgalitz** [comment]
Hi @dbwiddis we fixed this on main branch, feel free to close this issue if you confirmed on your end that this isn't blocking the `extensions` work

**Comment by dbwiddis** [comment]
I fixed it on our extensions branch in #686, I was just trying to be helpful and copy that fix here... I think we're all in sync now.
