### ISSUE TITLE
[BUG] Security enabled tests are failing on main branch

### ISSUE THREAD

**Issue by amitgalitz** [opensearch-project/anomaly-detection#712]
**What is the bug?**
All security enabled tests are failling in our current CI: https://github.com/opensearch-project/anomaly-detection/actions/runs/3348855024/jobs/5548340002

**How can one reproduce the bug?**
Follow the steps in this [workflow](https://github.com/opensearch-project/anomaly-detection/pull/710/files#diff-b19025fb2b6fa86c19a171b6e04a71bc04b26344358d2bd72288ea5106bef202R1)

In shorthand run docker from opensearchstaging:3.0.0 and run this command: `./gradlew integTest -Dtests.rest.cluster=localhost:9200 -Dtests.cluster=localhost:9200 -Dtests.clustername="docker-cluster" -Dhttps=true -Duser=admin -Dpassword=admin`

**What is the expected behavior?**
All tests pass
**What is your host/environment?**
 - OS: Linux
 - Version OS 3.0.0
 - Plugins AD and Security

**Do you have any additional context?**

Seems like the issue happens on all integ tests when security is enabled. We are getting unauthorized responses on our requests. This might be a breaking change either in security or OS core, meaning the way we send requests is out of date and needs to be changed. Will continue investigating and updating this issue as this might be faced by other plugins.
```
org.opensearch.ad.rest.SecureADRestIT > testGetApiFilterByEnabled FAILED
    org.opensearch.client.ResponseException: method [PUT], host [https://localhost:9200], URI [/_opendistro/_security/api/roles/index_all_access], status line [HTTP/2.0 401 Unauthorized]
    Unauthorized
        at app//org.opensearch.client.RestClient.convertResponse(RestClient.java:384)
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:354)
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:329)
        at app//org.opensearch.ad.TestHelpers.makeRequest(TestHelpers.java:213)
        at app//org.opensearch.ad.TestHelpers.makeRequest(TestHelpers.java:186)
        at app//org.opensearch.ad.AnomalyDetectorRestTestCase.createIndexRole(AnomalyDetectorRestTestCase.java:447)
        at app//org.opensearch.ad.rest.SecureADRestIT.setupSecureTests(SecureADRestIT.java:62)

    java.lang.NullPointerException
        at org.opensearch.ad.rest.SecureADRestIT.deleteUserSetup(SecureADRestIT.java:112)
        
```

**Comment by amitgalitz** [comment]
I think the issue might be that we are using "kibana" for the user-agent instead of "Opensearch-Dashboards". Will test this out and confirm and announce it to all plugins currently using "kibana"

**Comment by amitgalitz** [comment]
> I think the issue might be that we are using "kibana" for the user-agent instead of "Opensearch-Dashboards". Will test this out and confirm and announce it to all plugins currently using "kibana"

This wasn't enough to fix the issue, running the same commands from postman that are executed from the integ tests works manually. Also additionally the unauthorized issue is showing in java 11 and for java 17 it is a protocol error which is currently being fixed in common utils: https://github.com/opensearch-project/common-utils/pull/302/files

**Comment by kaituo** [comment]
@amitgalitz  @jackiehanyang  will solve it together with my benchmark PR. The issue is the client setup code in src/test/java/org/opensearch/ad/ODFERestTestCase.java:

```
-            credentialsProvider
-                .setCredentials(
-                    new AuthScope(new HttpHost("localhost", 9200)),
-                    new UsernamePasswordCredentials(userName, password.toCharArray())
-                );
+            final AuthScope anyScope = new AuthScope(null, -1);
+            credentialsProvider.setCredentials(anyScope, new UsernamePasswordCredentials(userName, password.toCharArray()));
```

**Comment by amitgalitz** [comment]
> @amitgalitz @jackiehanyang will solve it together with my benchmark PR. The issue is the client setup code in src/test/java/org/opensearch/ad/ODFERestTestCase.java:
> 
> ```
> -            credentialsProvider
> -                .setCredentials(
> -                    new AuthScope(new HttpHost("localhost", 9200)),
> -                    new UsernamePasswordCredentials(userName, password.toCharArray())
> -                );
> +            final AuthScope anyScope = new AuthScope(null, -1);
> +            credentialsProvider.setCredentials(anyScope, new UsernamePasswordCredentials(userName, password.toCharArray()));
> ```

Got it, thanks for helping solve this!

**Comment by kaituo** [comment]
fixed in the above PRs.
