### ISSUE TITLE
[BUG] Names don't adhere to plugin naming convention

### ISSUE THREAD

**Issue by mnkugler** [opensearch-project/anomaly-detection#741]
**What is the bug?**
As per https://github.com/opensearch-project/opensearch-plugins/blob/main/CONVENTIONS.md#opensearch-plugins, the folder name needs to adhere to the naming convention

**What is the expected behavior?**
[Folder needs to be created and Include full plugin name in kebab case, e.g., plugins/opensearch-anomaly-detection](https://github.com/opensearch-project/opensearch-plugins/blob/main/CONVENTIONS.md#folders)

**Do you have any additional context?**
Referred to here:
https://github.com/opensearch-project/opensearch-plugins/issues/174

**Comment by amitgalitz** [comment]
HI @mnkugler I'm a little confused what this change is exactly referring to. We don't have a `plugins` folder in our repository that would allow us to adhere to `plugins/opensearch-anomaly-detection`. Our current code is `src` which I assumed to be the standard for all plugins.

**Comment by mnkugler** [comment]
Hi @amitgalitz -- apologies. I realized that the naming convention I was referring to is outdated with respect to folders. We are removing the folders naming requirements since we are moving to one plugin per repo, as per https://github.com/opensearch-project/opensearch-build/issues/2188 and I'm working on a pull request to fix the wording. We can close this issue.
