### ISSUE TITLE
Baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions

### ISSUE THREAD

**Issue by dblock** [opensearch-project/anomaly-detection#808]
Follow https://github.com/opensearch-project/.github/issues/125 to baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions.

Close this issue when:

1. [MAINTAINERS.md](MAINTAINERS.md) has the correct list of project maintainers.
2. [CODEOWNERS](CODEOWNERS) exists and has the correct list of aliases.
3. Repo permissions only contain individual aliases as collaborators with maintain rights, admin, and triage teams. 
4. All other teams are removed from repo permissions.

If this repo's permissions was already baselined, please confirm the above when closing this issue.

**Comment by kaituo** [comment]
@dblock for repo permissions, did you meant https://github.com/orgs/opensearch-project/teams/anomaly-detection/members ?

**Comment by dblock** [comment]
Yes @kaituo

**Comment by dblock** [comment]
Verified permissions.
<img width="874" alt="Screenshot 2023-05-10 at 6 03 22 PM" src="https://github.com/opensearch-project/anomaly-detection/assets/542335/c3aec4c1-06a6-4cb0-a3b3-4e8e4ba1d325">
