### ISSUE TITLE
[Testing Confirmation] Confirm current testing requirements

### ISSUE THREAD

**Issue by scrawfor99** [opensearch-project/anomaly-detection#814]
As part of the discussion around implementing an organization-wide testing policy, I am visiting each repo to see what tests they currently perform. I am conducting this work on GitHub so that it is easy to reference. 

Looking at the Anomaly Detection repository, it appears there is 

| Repository  | Unit Tests | Integration Tests | Backwards Compatibility Tests | Additional Tests | Link | 
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | 
| Anomaly Detection | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> | Link checker, AD benchmark, Certificate of Origin | https://github.com/opensearch-project/anomaly-detection/issues/814 | 

I don't see any requirements for code coverage in the testing documentation. If there are any specific requirements could you respond to this issue to let me know? 

If there are any tests I missed or anything you think all repositories in OpenSearch should have for testing please respond to this issue with details.

**Comment by kaituo** [comment]
@scrawfor99 One requirement I have mind: we have some stats on the failing tests when a PR is merged and if some tests are flaky (e.g., 10% of the time failed) the repo owner needs to find a way to fix it.

**Comment by scrawfor99** [comment]
Hi @kaituo, thank you for following up. I will make a note and be sure to add your feedback.

**Comment by kaituo** [comment]
close since long time inactivity.
